name: Deploy Next.js to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install and build Next.js
        run: |
          npm ci
          npm run build
        env:
          CI: true

      - name: Deploy Next.js to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/modern-stack-hackathon
            git reset --hard origin/main
            git pull origin main
            npm ci
            npm run build
            pm2 restart modern-stack-hackathon-next --update-env || pm2 start npm --name "modern-stack-hackathon-next" -- start
